# Generated by Django 4.2.7 on 2025-08-05 17:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('factor_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_households', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReductionTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('energy', 'Energy'), ('transportation', 'Transportation'), ('diet', 'Diet'), ('waste', 'Waste'), ('water', 'Water'), ('general', 'General')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('potential_savings', models.FloatField(help_text='Potential CO2 savings in kg per year')),
                ('cost_estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', '-potential_savings'],
            },
        ),
        migrations.CreateModel(
            name='UserReductionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tracker.household')),
                ('reduction_tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.reductiontip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('car_gasoline', 'Car (Gasoline)'), ('car_diesel', 'Car (Diesel)'), ('car_hybrid', 'Car (Hybrid)'), ('car_electric', 'Car (Electric)'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('train', 'Train'), ('subway', 'Subway'), ('flight_domestic', 'Flight (Domestic)'), ('flight_international', 'Flight (International)'), ('bike', 'Bicycle'), ('walk', 'Walking')], max_length=30)),
                ('distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('frequency', models.CharField(default='daily', max_length=20)),
                ('fuel_efficiency', models.FloatField(blank=True, null=True)),
                ('date_recorded', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='tracker.household')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Natural Gas'), ('oil', 'Heating Oil'), ('propane', 'Propane'), ('coal', 'Coal'), ('solar', 'Solar'), ('wind', 'Wind')], max_length=20)),
                ('usage_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='kWh', max_length=20)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_recorded', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_usage', to='tracker.household')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('flexitarian', 'Flexitarian')], max_length=20)),
                ('food_category', models.CharField(choices=[('meat_beef', 'Beef'), ('meat_pork', 'Pork'), ('meat_chicken', 'Chicken'), ('meat_lamb', 'Lamb'), ('fish', 'Fish'), ('dairy', 'Dairy Products'), ('eggs', 'Eggs'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('processed', 'Processed Foods')], max_length=20)),
                ('weekly_consumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('local_sourced_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('organic_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_recorded', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to='tracker.household')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('energy_emissions', models.FloatField(default=0.0)),
                ('transportation_emissions', models.FloatField(default=0.0)),
                ('diet_emissions', models.FloatField(default=0.0)),
                ('total_emissions', models.FloatField(default=0.0)),
                ('per_capita_emissions', models.FloatField(default=0.0)),
                ('national_average', models.FloatField(blank=True, null=True)),
                ('global_average', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footprints', to='tracker.household')),
            ],
            options={
                'ordering': ['-calculation_date'],
                'unique_together': {('household', 'calculation_date')},
            },
        ),
    ]
